#include "TestArraysSolutions.hpp"
#include "TestBitArray.hpp"
#include "TestCanTwoMoviesFillFlight.hpp"
#include "TestCountingValleys.hpp"
#include "TestDutchNationalFlag.hpp"
#include "TestFindUnsortedSubarray.hpp"
#include "TestInheritedCode.hpp"
#include "TestLinkedListSolutions.hpp"
#include "TestLongestCommonSubsequence.hpp"
#include "TestLongestIncreasingSubsequence.hpp"
#include "TestMakeChange.hpp"
#include "TestMatrixProduct.hpp"
#include "TestMaximumContiguousSum.hpp"
#include "TestMergeMeetings.hpp"
#include "TestMergeVectors.hpp"
#include "TestMinSwapsArray.hpp"
#include "TestMoveAllZerosToTheEnd.hpp"
#include "TestProductsOfAllIntsExceptAtIndex.hpp"
#include "TestReverseArrayTraversal.hpp"
#include "TestReverseContainer.hpp"
#include "TestReverseSentence.hpp"
#include "TestReverseStringInPlace.hpp"
#include "TestReverseWords.hpp"
#include "TestSortThreeEnumArrays.hpp"
#include "TestTemplateSpecialization.hpp"
#include "TestTwoSumInwardIteration.hpp"

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}