# borrowed from https://github.com/bsamseth/cpp-project/blob/master/.travis.yml

sudo: false
language: cpp
dist: xenial
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgtest-dev
            - cmake
            - cmake-data
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7 && CXX=g++-7 && CC=gcc-7 && CXXSTD=c++14"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cp -r /usr/src/gtest/* ./
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - mkdir include && cp -r /usr/include/gtest include
  - mkdir lib && cp libgtest* lib
  - cd -

script:
  - export GTEST_COLOR=1
  - export GTEST_ROOT="~/gtest"  
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - cmake --build . --config Debug --target test_everything

after_success:
  - if pyenv shell 3.6.3; then pip3 install --user codecov; fi
  - if $CXX_COMPILER test/main.cpp -std=$CXXSTD -Isrc -Wall -pedantic -O0 --coverage -ftest-coverage -fprofile-arcs -lgcov -o test_everything; then ./test_everything; fi
  - bash <(curl -s https://codecov.io/bash) -X coveragepy -x gcov-7 -a --relative-only
